name: Deploy unleash
on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      env_name:
        description: 'Milj√∏ som det skal deployes til'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  deploy_unleash:
    runs-on: ubuntu-latest
    name: Deploy unleash
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v6
      - name: Deploy unleash to prod-gcp
        uses: nais/deploy/actions/deploy@v2
        if: github.event.inputs.env_name == 'prod' || github.ref == 'refs/heads/main'
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/unleash.yaml
          VARS: .nais/prod.yaml
      - name: Deploy unleash to dev-gcp
        uses: nais/deploy/actions/deploy@v2
        if: github.event.inputs.env_name == 'dev' || github.ref != 'refs/heads/main'
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/unleash.yaml
          VARS: .nais/feature.yaml